Update to crest 3.0.1
conda-forge/crest-feedstock pull request #12
Opened 2024-06-12 14:43 UTC by maxscheurer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-06-12 15:44 UTC, maxscheurer commented
If anyone knows how to fix the "undefined reference to..." error, that would be great 😁

2024-06-12 17:23 UTC, awvwgk requested changes
Also, please remove the static library from the package as those should not be included in the distribution for cf.

2024-06-12 17:23 UTC, awvwgk commented on recipe/meta.yaml
>      - liblapack
```suggestion
    - liblapack
    - tblite
```

2024-06-12 17:23 UTC, awvwgk commented on recipe/meta.yaml
> +    - tblite
```suggestion
```

2024-06-12 17:24 UTC, awvwgk commented on recipe/meta.yaml
>    build:
```suggestion
  build:
    - {{ stdlib('c') }}
```

2024-06-12 20:27 UTC, maxscheurer commented
@conda-forge-admin, please rerender.

2024-08-26 06:34 UTC, closed without merging

2024-08-26 06:34 UTC, maxscheurer commented
Superseded by #13